"use client";
import { FormEvent, useMemo, useState } from "react";
import { splitRuleText } from "@/lib/shared/chunking";

export default function AdminPage() {
  const [title, setTitle] = useState(""); const [category, setCategory] = useState("지원 서류"); const [content, setContent] = useState(""); const [status, setStatus] = useState("초안"); const [message, setMessage] = useState("");
  const chunks = useMemo(() => splitRuleText(content), [content]);
  async function index(event: FormEvent) { event.preventDefault(); setStatus("임베딩 중"); setMessage(""); try { const response = await fetch("/api/rules/index", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title, category, content }) }); const data = await response.json() as { chunkCount?: number; error?: string }; if (!response.ok) throw new Error(data.error); setStatus("완료"); setMessage(`${data.chunkCount}개 청크를 임베딩해 Firestore에 저장했습니다.`); } catch (error) { setStatus("실패"); setMessage(error instanceof Error ? error.message : "처리에 실패했습니다."); } }
  return <main className="adminShell"><span className="eyebrow">KNOWLEDGE PIPELINE</span><h1>취업 규칙 인덱싱</h1><p className="subtle">원문을 청킹해 확인한 뒤 Vertex AI 임베딩과 Firestore Vector Search에 저장합니다.</p><div className="pipeline"><b>1. 원문</b><span>→</span><b>2. 청크 미리보기</b><span>→</span><b>3. 임베딩</b><span>→</span><b>4. 검색 준비</b></div><div className="indexGrid"><form className="ruleForm" onSubmit={index}><label>규칙 제목<input required value={title} onChange={(e) => setTitle(e.target.value)} placeholder="예: 신입 지원 이력서 기준" /></label><label>분류<select value={category} onChange={(e) => setCategory(e.target.value)}><option>지원 서류</option><option>면접</option><option>지원 자격</option><option>채용 일정</option><option>기타</option></select></label><label>규칙 원문<textarea required value={content} onChange={(e) => setContent(e.target.value)} rows={14} placeholder="규칙 전문을 붙여 넣으세요. 제목/조항 단위의 빈 줄을 유지하면 검색 품질이 좋아집니다." /></label><div className="statusLine"><span>상태: <b>{status}</b></span><span>{content.length.toLocaleString()}자 · {chunks.length}개 예상 청크</span></div><button disabled={status === "임베딩 중" || chunks.length === 0}>청크 임베딩 및 저장</button>{message && <p className={status === "실패" ? "inlineError" : "successMessage"}>{message}</p>}</form><aside className="previewCard"><div><h2>청크 미리보기</h2><small>약 900자 · 120자 중첩</small></div>{chunks.length === 0 ? <p className="muted">규칙 원문을 입력하면 청크가 표시됩니다.</p> : <div className="chunkList">{chunks.map((chunk) => <article key={chunk.index}><span>CHUNK {chunk.index} · {chunk.section}</span><p>{chunk.text}</p></article>)}</div>}</aside></div></main>;
}
